### PR TITLE
[FDP-566] Set headers in HTTP proxy of client

### PR DESCRIPTION
**Pull request by MarekSuchanek**

### CODE REVIEW

**Review by kburger — APPROVED** [review]
That regex looks [complex](https://regexper.com/#~%5E%28%2C%5B%20%5C%5Ct%5D*%29*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%28%5B%20%5C%5Ct%5D*%2C%28%5B%20%5C%5Ct%5D*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%29%3F%29*%24)! Any way we can make that a bit more maintainable/understandable?

**Comment by MarekSuchanek** [comment]
@kburger The 

> That regex looks [complex](https://regexper.com/#~%5E%28%2C%5B%20%5C%5Ct%5D*%29*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%28%5B%20%5C%5Ct%5D*%2C%28%5B%20%5C%5Ct%5D*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%29%3F%29*%24)! Any way we can make that a bit more maintainable/understandable?

Its based on [this](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/), how `Forwarded` should look like. But we can use just the conventional `X-Forwarded-IP` and do not bother with `Forwarded` headers at all. Should I remove it for the sake of maintainability?

**Comment by kburger** [comment]
> @kburger The
> 
> > That regex looks [complex](https://regexper.com/#~%5E%28%2C%5B%20%5C%5Ct%5D*%29*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%28%5B%20%5C%5Ct%5D*%2C%28%5B%20%5C%5Ct%5D*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%29%3F%29*%24)! Any way we can make that a bit more maintainable/understandable?
> 
> Its based on [this](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/), how `Forwarded` should look like. But we can use just the conventional `X-Forwarded-IP` and do not bother with `Forwarded` headers at all. Should I remove it for the sake of maintainability?

If we can always fall back to (or refer to) the official nginx docs, I'm happy. We can leave it in.

**Comment by MarekSuchanek** [comment]
> > @kburger The
> > > That regex looks [complex](https://regexper.com/#~%5E%28%2C%5B%20%5C%5Ct%5D*%29*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%28%5B%20%5C%5Ct%5D*%2C%28%5B%20%5C%5Ct%5D*%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%28%3B%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%3D%28%5B!%23%24%25%26'*%2B.%5E_%60%7C~0-9A-Za-z-%5D%2B%7C%5C%22%28%5B%5C%5Ct%20%5C%5Cx21%5C%5Cx23-%5C%5Cx5B%5C%5Cx5D-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%7C%5C%5C%5C%5C%5B%5C%5Ct%20%5C%5Cx21-%5C%5Cx7E%5C%5Cx80-%5C%5CxFF%5D%29*%5C%22%29%29%3F%29*%29%3F%29*%24)! Any way we can make that a bit more maintainable/understandable?
> > 
> > 
> > Its based on [this](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/), how `Forwarded` should look like. But we can use just the conventional `X-Forwarded-IP` and do not bother with `Forwarded` headers at all. Should I remove it for the sake of maintainability?
> 
> If we can always fall back to (or refer to) the official nginx docs, I'm happy. We can leave it in.

OK, simplified 🙂

**Review by janslifka — APPROVED** [review]

**Pull request merged**
